name = "chronospect-website"
compatibility_date = "2024-03-24"

[site]
bucket = "./dist"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "chronospect-website-prod"
route = "chronospect.com/*"

pages_build_output_dir = "dist" 